### ISSUE TITLE
Some modifications from other forks

### ISSUE THREAD

**Issue by AbuBaniaz** [LraiZer/RadiotimesXmltvEmulator#8]
Are any changes done to these forks of any benefit?

https://github.com/dave-p/openTVtoXML
https://github.com/dave-p/openTVtoXML/compare/standalone...jahutchi:openTVtoXML:standalone

**Comment by LraiZer** [comment]
there is no extra data modifications from dave-p or jahutchi that engima2 is currently coded to read from the generated xmltv.

i have already primed engima2 to [read the ratings and genre data here](https://github.com/OpenViX/enigma2/blob/0bf8710f916d4fb3dbb6763153a9e61e8a568380/lib/dvb/opentv.cpp#L177-L180). ratings are not standard from county to country, so that data has an added complexity.

dave-p forked due to the opentv epg in tvheadead being broken a couple of years ago. this tool was used as a temporary workaround to inject the stream data into tvheadend and was forked and adjusted to be compatible with that requirement.

at that time tvheadend was only using the eventid to match, when the correct way, as is done in this tool and engima2 patch is a combination of channelid and eventid.

jahutchi fork saw channelid and eventid was required and fixed this in the [tvheadend patch here](https://github.com/tvheadend/tvheadend/commit/1ee9c5b9cc516d37cb55a9d924a4ca854a64f720) so this tool is not needed anymore with tvheadend.

**Comment by AbuBaniaz** [comment]
Thanks.
